samples/WebApp samples/WebApp/Models/Transport.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Threading.Tasks;
using TotalApi.Core.Events;
using TotalApi.Telematics;

namespace WebApp.Models
{
    public class Transport
    {
        public Transport() : this(true)
        {
        }

        public Transport(bool clear)
        {
            if (clear)
                Clear();
        }

        public static List<Transport> Transports = new List<Transport>
        {
            new Transport(false) {Id = "1", Name = "Tr1", DeviceIdentifier = DeviceIdentifier.OwnId("05b5607d-a0d1-4a09-8c27-5e908c64c32f")},
            new Transport(false) {Id = "2", Name = "Tr2", DeviceIdentifier = DeviceIdentifier.OwnId("7a80275e-a43e-4f84-b20c-572b16503e08") },
            new Transport(false) {Id = "3", Name = "Tr3", DeviceIdentifier = DeviceIdentifier.PhoneNumber("+822542119082") },
            new Transport(false) {Id = "4", Name = "Tr4", DeviceIdentifier = DeviceIdentifier.PhoneNumber("+704337715079") }
        };
        private void Clear()
        {
            Task.Delay(TimeSpan.FromMinutes(60)).ContinueWith(r =>
            {
                Transports.Remove(this);
                OnDataChanged.Publish(typeof(Device), TelematicsApi.Telematics.FindDevice(DeviceIdentifier).Id, OnDataChanged.Action.Delete);
            });
        }

        public string Id { get; set; }

        public string Name { get; set; }

        public DeviceIdentifier DeviceIdentifier { get; set; }

        [NotMapped]
        public Device Device { get; set; }

        [NotMapped]
        public DeviceStatus LastStatus { get; set; }
    }
}

samples/WebApp samples/WebApp/Controllers/BenchmarkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApp.Controllers
{
    public class BenchmarkController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Title = "Benchmark";

            return View();
        }
    }
}

samples/WebApp samples/WebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Title = "Map";

            return View();
        }
    }
}

samples/WebApp samples/WebApp/Controllers/SDKController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApp.Controllers
{
    public class SDKController : Controller
    {
        // GET: SDK
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Modules()
        {
            return View();
        }

        public ActionResult AsyncTasks()
        {
            return View();
        }

        public ActionResult Events()
        {
            return View();
        }

        public ActionResult Repository()
        {
            return View();
        }

        public ActionResult Telematics()
        {
            return View();
        }

        public ActionResult Authentication()
        {
            return View();
        }
    }
}

samples/WebApp samples/WebApp/Controllers/SharedController.cs
using System.Web.Mvc;

namespace WebApp.Controllers
{
    public class SharedController : Controller
    {
        public ActionResult Index(string s)
        {
            throw new System.NotImplementedException();
        }
    }
}

samples/WebApp samples/WebApp/Controllers/TransportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApp.Api;

namespace WebApp.Controllers
{
    public class TransportController : Controller
    {
        // GET: Transport
        public ActionResult Index()
        {
            ViewBag.Title = "Transport";
            return View();
        }
        // GET: Transport/Edit/
        public ActionResult Edit()
        {
            ViewBag.Title = "Edit Transport Item";
            return View("EditTransportItem");
        }
    }
}

samples/WebApp samples/WebApp/Views/Benchmark/Index.cshtml
<div class="container">
    <div class="col-md-8 col-md-offset-2">
        <div class="panel panel-primary form-panel">
            <div class="panel-heading">Benchmark</div>
            <div class="panel-body">
                <form>
                    <fieldset class="period-select">
                        <legend>Select the period (min - 1, max - 48 hours)</legend>
                        <div class="label label-info range-display">24</div>
                        <div class="form-group">
                            <input type="range" class="range-input" value="24" min="1" max="48">
                        </div>
                        <button type="submit" class="btn btn-success button-load">Load</button>
                    </fieldset>
                </form>
            </div>
        </div>
        <div class="msg-box"></div>
    </div>
</div>

@section scripts {
    <script src="~/Scripts/app/benchmark.js"></script>
}

samples/WebApp samples/WebApp/Views/Home/Index.cshtml
<div class="container-fluid">
    <div id="map" class="map-container"></div>
    <button class="btn btn-danger button-clear-track" disabled>Clear track</button>
</div>

@section scripts {
    <script src="~/Scripts/app/map.js"></script>
}

samples/WebApp samples/WebApp/Views/SDK/AsyncTasks.cshtml
<div class="container">

    <h2 class="sdk_sample_step">Async tasks</h2>

    <a class="stepProject" href="#">AsyncTasks</a>

    <div class="sdk_content">

        <h2>Functions overview</h2>
        <p>
            <ul>
                <li>
                    Getting a list of tasks
                </li>
                <li>
                    Tasks management (start/cancel/suspend/resume/remove)
                </li>
                <li>
                    Getting current task status/result
                </li>
                <li>
                    Configuring tasks settings
                </li>
                <li>
                    Generation of AsyncTasks API events
                </li>
            </ul>
        </p>

        <p>
            To manage any asynchronous distributed tasks a universal API used, called AsyncTasks API. 
            This API is the base for other API, which implements specific asynchronous tasks (for example, some report generation ).
        </p>

        <h2>Tasks settings</h2>
        <p>
            These settings affects the execution and storing the results, but do not affect the data returned by these tasks. 
            This, for example, the storage of the results, caching time results timeout implementation, etc.
        </p>

        <h2>
            The identifier of the task - AsyncTaskId
        </h2>
        <p>
            At the start of asynchronous task, service method returns the process id of the task.
            This string value can be used for further work with this task (getting the current status of execution, cancellation, results). 
            Furthermore, during execution, the module fires event called OnProgress in which instanceId property is actually AsyncTaskId.
        </p>

        <h2>Avaliable tasks events</h2>

        <h3>OnAsyncTaskStarted</h3>

        <p>Fires when task is started</p>
        <table class="table table-striped table-bordered table-hover table-condensed table-responsive">
            <thead>
                <tr>
                    <td>
                        Property
                    </td>
                    <td>
                        Description
                    </td>
                    <td>
                        Type
                    </td>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>taskId</td>
                    <td>Task identifier</td>
                    <td>string</td>
                </tr>
            <tr>
                <td>task</td>
                <td>Task parameters, also declares task type</td>
                <td>AsyncTaskObject</td>
            </tr>
            </tbody>
        </table>

        <h3>OnAsyncTaskFinished</h3>

        <p>Fires when task is finished</p>
        <table class="table table-striped table-bordered table-hover table-condensed table-responsive">
            <thead>
                <tr>
                    <td>
                        Property
                    </td>
                    <td>
                        Description
                    </td>
                    <td>
                        Type
                    </td>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>taskId</td>
                    <td>Task identifier</td>
                    <td>string</td>
                </tr>
            <tr>
                <td>task</td>
                <td>Task parameters, also declares task type</td>
                <td>AsyncTaskObject</td>
            </tr>
                <tr>
                    <td>Status</td>
                    <td>Task execution status</td>
                    <td>AsyncTaskStatus</td>
                </tr>
            </tbody>
        </table>

        <h3>OnProgress</h3>

        <p>Fires task execution progress is changing</p>
        <table class="table table-striped table-bordered table-hover table-condensed table-responsive">
            <thead>
                <tr>
                    <td>
                        Property
                    </td>
                    <td>
                        Description
                    </td>
                    <td>
                        Type
                    </td>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>instanceId</td>
                    <td>Task identifier</td>
                    <td>string</td>
                </tr>
                <tr>
                    <td>progress</td>
                    <td>Current task progress value</td>
                    <td>int</td>
                </tr>
                <tr>
                    <td>statusText</td>
                    <td>Task execution status text</td>
                    <td>string</td>
                </tr>
            </tbody>
        </table>


        <h2>Sample code overview</h2>

        <h3>Creating task</h3>

        <p>
            To allow using custom modules you need to create class derived from AsyncTaskObject, the name of this class will be determined as the event name.
            To implement the logic of the task, you need to create a handler class, derived from <b>AsyncTaskHandler&lt;TTask, TResult&gt;</b>, and export it as IAsyncTaskHandler.
            After implementing logic in overriden Start method, the task will be ready.
        </p>

        <h3>Creating task event</h3>

        <p>
            Both OnAsyncTaskStarted and OnAsyncTaskFinished events are derived from OnAsyncTaskEvent class.
            We can use this class to create a custom event that could be fired during asynk task execution.
            In the sample code we created class called CustomAsyncTaskEvent, the only change from the base class is custom string Message property.
            So, we can now fire this event through CoreApi.EventManager.Publish(...) method.
            To catch this event, you need to use subscriber class, that must implement generic interface <b>IEvent&lt;TTaskEvent&gt;</b> of a newly created task event
</p>



    </div>

</div>

samples/WebApp samples/WebApp/Views/SDK/Authentication.cshtml
<div class="container">

    <h2 class="sdk_sample_step">Authentication</h2>

    <div class="sdk_content">

        <h3>Authentication overview</h3>

        <p>
            TotalApi authentication - transfering authentication info to services during calling API services.
            <a href="http://localhost:30098/Help/ResourceModel?modelName=TotalApiAuth">TotalApiAuth</a> class, representing authentication information described <a href="#">here</a>.
        </p>

        <h3>Terms of authentication model</h3>

        <table class="table table-striped table-bordered table-hover table-condensed table-responsive">
            <thead>
                <tr>
                    <td>
                        Property
                    </td>
                    <td>
                        Description
                    </td>
                    <td>
                        Type
                    </td>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>ApiKey</td>
                    <td>Unique and secret key to access the API.</td>
                    <td>string</td>
                </tr>
                <tr>
                    <td>SSID</td>
                    <td>Subsystem identifier. Needed only for calling the methods of billing subsystem.</td>
                    <td>string</td>
                </tr>
                <tr>
                    <td>AppKey</td>
                    <td>
                        Unique public key for applications.
                        Distributed with ApiKey when registering a new user application - the API user.
                        It makes sense only if a third-party developer, bought ApiKey, developing their client (mobile, desktop or js). application, 
                        and does not want to publish the ApiKey on the client side.
                    </td>
                    <td>string</td>
                </tr>
            <tr>
                <td>UserLogin</td>
                <td>
                    Returns user login for AppUser authorization.
                    If UserLogin is not set or UserLogin is set but AppKey is not set - throw an authorization exception.
                </td>
                <td>string</td>
            </tr>
            <tr>
                <td>UserPassword</td>
                <td>
                    Returns UserPassword for AppUser authorization.
                    If UserLogin is not set or UserLogin is set but AppKey is not set - throw an authorization exception.
                </td>
                <td>string</td>
            </tr>
            <tr>
                <td>ClientId</td>
                <td>
                    The unique identifier of a specific instance of the client application.
                    It may be generated at the start of the application.
                    It does not affect the authentication, but is important to optimize the transmission of notifications between instances of the client applications.
                </td>
                <td>string</td>
            </tr>
                <tr>
                    <td>SessionKey</td>
                    <td>
                        Identifier of a temporary session.
                        Alternative AppKey use on the client side.
                        Using ApiKey or AppUser authorization, the client receives a temporary session token, which can only be used for this session some time. 
                        Compromise of this token bears no threat to security, because it is valid for a short time, and only for that session.
                    </td>
                    <td>string</td>
                </tr>
            </tbody>
        </table>

        <h3>Authentication </h3>

        <p>
            Authentication infornmation could be delivered to the services by one of three possible ways:
        </p>
        <ul>
            <li>
                Delivering <a href="http://localhost:30098/Help/ResourceModel?modelName=TotalApiAuth">TotalApiAuth</a> json object as the parameter of api's endpoint url, for example:
                <a href="#">https://s1.totalapi.com/totalapi/api/v1/wcf/ITelematicsService?auth={ApiKey:”456”}</a>
            </li>
            <li>
                Delivering <a href="http://localhost:30098/Help/ResourceModel?modelName=TotalApiAuth">TotalApiAuth</a> json object in Authorization header of HTTP request:
                Authorization: {ApiKey:”456”}
            </li>
            <li>
                Delivering <a href="http://localhost:30098/Help/ResourceModel?modelName=TotalApiAuth">TotalApiAuth</a> json object in Authorization header of WCF request (only for WCF API):
            </li>
        </ul>
        <p>
            Depending on delivered authentication info, several authorization modes are avaliable:
        </p>

        <h3>ApiKey authorization</h3>
        <p>
            ApiKey property filled correctly. Used for direct work with API (in a web application backend, for example).
            Full access to all data connected to provided ApiKey are avaliable.
        </p>

        <h3>AppKey authorization</h3>
        <p>
            ApiKey property is filled with a valid value.
            ApiKey and SSID properties is not specified.
            Can be used exclusively in third-party client applications to register a new user of the application.
        </p>

        <h3>AppUser authorization</h3>
        <p>
            ApiKey, UserLogin, UserPassword properties filled with valid values.
            ApiKey and the SSID property is not filled.
            Used exclusively in third-party client applications to work with data API, limited only to the specified user.
        </p>

        <h3>SessionKey authorization</h3>
        <p>
            SessionKey property is filled with a valid value obtained by calling GetSessionKey method.
            AppKey, UserLogin, UserPassword, ApiKey and the SSID property is not filled.
            Used in client applications for working with data API directly from the frontend.
            The level of access to the API is the same as calling GetSessionKey method.
        </p>


    </div>

</div>

samples/WebApp samples/WebApp/Views/SDK/Events.cshtml
<div class="container">

    <h2 class="sdk_sample_step">Events</h2>

    <a class="stepProject" href="#">Events</a>

    <script type="text/C#" id="event">
        ///<summary>
        /// Sample event class. Just a simple class.
        ///</summary>
        internal class SampleEventClass
        {
            public readonly string Message;
            public SampleEventClass(int num)
            {
                Message = string.Format("Sample event message {0}", num);
            }
        }

        ///<summary>
        /// Subscriber for the events.
        ///</summary>
        internal class Subscriber : IEvent<SampleEventClass>//, you can implement several interfaces here, to support different events
        {
            private static readonly Lazy<Subscriber> _instance = new Lazy<Subscriber>(() => new Subscriber());
            public static Subscriber Instance { get { return _instance.Value; } }

            public void HandleEvent(SampleEventClass e)
            {
                ColorConsole.Do(ConsoleColor.Yellow, () =>
                {
                    Console.WriteLine("Event received: {0}", e.Message);
                });
            }
        }
    </script>

    <div class="sdk_content">

        <h2>Functions overview</h2>

        <ul>
            <li>
                Subscribing/Unsubscribing to events
            </li>
            <li>
                Receiving new events
            </li>
            <li>
                Events publishing    
            </li>
        </ul>

        <p>
            API is implemented by the module. 
            This module must be present in any subsystem, which publishes its own events or receives the events from outside.
        </p>

        <p>
            Each subsystem should return a list of events that this subsystem can send to other subsystems. 
            If an empty list given - subscribing to events from other sub-systems will not be applied.
        </p>

        <p>
            Each subsystem should return a list of events that it can handle and which comes from other subsystems.
            If an empty list given - the subsystem will not receive events from other subsystems. 
            If the list wil contain the string "*" - subsystem will receive all the events.
        </p>

        <h2>Sample code overview</h2>

        <p>
            SDK contains TotalApiEventObject class - the base class for any existing or new event. You should create the class, derived from this, to be able to publish the event. 

            TotalApiEventObject includes (optionally) information about access rights.
            If ApiKey is not set - event will not be avaliable to subscribers,
            otherwise if UserId is not set - event will be avaliable to all subscribers, authorized by ApiKey,
            if UserId is set - additionally, only for subscribers with correspondent UserKey authorization.
        </p>

        <p>
            In addition to TotalApiEventObject, there is an InternalEventObject class.
            Events, derived from this class would not be distributed to external subsystems.
            They will circulate only within a particular subsystem.
        </p>

        <pre class="brush: csharp" sample-id="event"></pre>

    </div>

</div>

samples/WebApp samples/WebApp/Views/SDK/Modules.cshtml
<div class="container">

    <h2 class="sdk_sample_step">Developing modules</h2>

    <a class="stepProject" href="#">Modules</a>

    <script id="moduleNames" type="text">
        TotalApi.{ModuleName}             //Service module part (for isolated module - this will is the only assembly)
        TotalApi.{ModuleName}.{DbType}    //Service module part that implements IDbConext interface for working with module database (not neccessary)
        TotalApi.{ModuleName}.Api         //Common part for service and client parts (interfaces definitions, POCO data models, extensions and helpers etc.)
        TotalApi.{ModuleName}.Client      //Client module part
    </script>

    <script id="moduleProxy" type="text">[Export(typeof(I{ModuleName}))]
        class {ModuleName}Client : I{ModuleName} { /* Implementation here */ }
    </script>

    <script id="moduleLocal" type="text">[Export(typeof(IFactory<I{ServiceContract}>))]
        class {ServiceContract}ServiceProxy : IFactory<I{ServiceContract}> { /* Implementation here */ }
    </script>

<script id="moduleDistributed" type="text">[Export(typeof(IFactory<I{ServiceContract}>))]
class {ServiceContract}ServiceProxy : ApiServiceProxy<I{ServiceContract}> { /* Implementation here */ }
</script>

<script id="moduleOrder" type="text">[Order(/* Order integer value*/)]
[Export(typeof(IModuleInitializer))]
class Startup : IModuleInitializer
{
    public void Init()
    {
        /* Do some stuff */
    }
}
</script>

    <div class="sdk_content">

        <h3>Introduction</h3>

        <p>
            Modules can be isolated, service and client.
        </p>

        <p>
            Isolated Module - a module that does not have its own interface and interact with the system only
            using interfaces of other modules (e.g. through the Repository module or Events module).
        </p>

        <p>
            Service modules - modules that executes on subsystem's core and implements its own API to the outside world through the WCF/WEB-services.
        </p>

        <p>
            If we want to use the API of the service modules - we need to use the client module that implements the API of that
            module by calling the appropriate WCF/WEB-service methods.
        </p>


        <h3>Creating modules</h3>

        <p>
            1. Module must be located in folder $(SolutionDir)\Modules\{ModuleName}
        </p>

        <p>
            2. Module assemblies must have the following names:

            <pre class="brush: csharp;" sample-id="moduleNames"></pre>
        </p>

        <p>
            3. If module is isolated - no additional actions are necessary.
        </p>

        <p>
            4. The client module should include two classes:

            
            The proxy class implementation of isolated module's API interface:
            <pre class="brush: csharp;" sample-id="moduleProxy"></pre>

            The proxy class implementation of service module's API interface:

            <ul>
                <li>
                    For a proxy class of not distributed module.

                    <pre class="brush: csharp;" sample-id="moduleLocal"></pre>
                </li>
                <li>
                    For a proxy class of distributed module.

                    <pre class="brush: csharp;" sample-id="moduleDistributed"></pre>
                </li>
            </ul>
           
            The difference in definitions is due to the fact that the distributed module itself should support the external API
            for Repository interface of its own business objects (IRepositoryApi) and this is already implemented in the class ApiServiceProxy<>.
            It is not necessary for distributed modules to implement this interface, because it is already implemented in a standard isolated RepositoryApi module.
        </p>

        <p>
            5. Client module project might have assembly attribute [assembly: Guid()] (absolutelly required for distributed modules) equal to
            the corresponding value for this attribute in the main module. Provides correspondence between business objects jointly processed by a given pair of modules. 
            If such correspondence will be corrupted - the system can not guarantee the correct and optimal work with the RepositoryAPI of distributed modules.
        </p>

        <p>
            6. If you want to provide some initial setup for the module after loading, implement the following class:

            <pre class="brush: csharp;" sample-id="moduleOrder"></pre>
        </p>

        <p>
            In general, if a class implements and exports IModuleInitializer interface -
            method IModuleInitializer.Init() will be automatically fired after modules loading.
            If [Order] attribute defined - it will set the order of initialization methods calls.
        </p>
                              
    </div>

</div>

samples/WebApp samples/WebApp/Views/SDK/Telematics.cshtml
<div class="container">

    <h2 class="sdk_sample_step">Telematics</h2>

    <a class="stepProject" href="#">Telematics</a>

    <script type="text/C#" id="telematics">
        var device = CoreApi.Repository.ExecuteQuery<Device>().First();
        
        CoreApi.EventManager.Subscribe(Subscriber.Instance);
        
        TelematicsApi.Telematics.WriteCoordinates(DeviceIdentifier.DbId(device.Id), new List<Coordinate>
                {
                    new Coordinate(DateTime.UtcNow, 20, 30, 40, 50, 60, 0)
                });

        var status = TelematicsApi.Telematics.GetDeviceLastStatus(device.Id);
        
        var filteredTrack = TelematicsApi.Telematics.ReadCoordinates(DeviceIdentifier.DbId(device.Id));
        
        var fullTrack = TelematicsApi.Telematics.ReadCoordinates(DeviceIdentifier.DbId(device.Id), null, null, DBNull.Value);
    </script>

    <div class="sdk_content">

        <h3>Functions overview</h3>

        <ul>
            <li>
                Represents CRUD operations over devices and sensors.
            </li>
            <li>
                Declares events of devices/sensors changes, their telematics data and statuses.
            </li>
        </ul>

        <h3>Sample overview</h3>

        <p>Sample code includes some Telematics methods execution, like reading coordinates, creating new device, retrieving last status</p>

        <pre class="brush: csharp" sample-id="telematics"></pre>
            
        <p>
            Code on lines 12 and 14 are used for retrieving track or device. By default all filters are included, if no filters are set (line 12).
            In order to retrieve full track you need to pass DBNull.Value as filters parameter.
            You can setup filters by passing one or multiple filter parameters classes:

        </p>

        <ul>
            <li>BreaksFilterParameters</li>
            <li>RosePointsFilterParameters</li>
            <li>SimplificateFilterParameters</li>
            <li>SpeedFilterParameters</li>
            <li>StopsFilterParameters</li>
</ul>

    </div>

</div>

samples/WebApp samples/WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <script type="text/javascript" src="~/Scripts/shHighlight/shCore.js"></script>
    <script type="text/javascript" src="~/Scripts/shHighlight/shBrushCSharp.js"></script>
    <script type="text/javascript" src="~/Scripts/shHighlight/shBrushXml.js"></script>

    <link type="text/css" rel="stylesheet" href="~/Content/shHighlight/shCoreDefault.css"/>
    <link type="text/css" rel="stylesheet" href="~/Content/shHighlight/shCoreEmacs.css" />
    @*<link type="text/css" rel="stylesheet" href="~/Content/shHighlight/shThemeEmacs.css" />*@
    <script type="text/javascript"></script>

    @Styles.Render("~/Content/css")

    @Scripts.Render("~/bundles/jquery")

    <style>
        .library {
            color: Maroon;
            font-weight: Bold;
        }

        .setting {
            color: rgb(255, 145, 92);
            font-weight: Bold;
        }

        .codeMethod {
            color: Brown;
        }

        .stepResult {
        }

        .stepProject {
        }
    </style>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("SDK Samples", "Index", "SDK", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Map", "Index", "Home")</li>
                    <li>@Html.ActionLink("Transport", "Index", "transport")</li>
                    <li>@Html.ActionLink("Benchmark", "Index", "benchmark")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container-fluid body-content">
        @RenderBody()
    </div>

 
    @Scripts.Render("~/bundles/bootstrap")

    <script src="~/signalr/hubs"></script>

    @Scripts.Render("~/bundles/app")


    @RenderSection("scripts", required: false)

<script>
    
    var samples = $("pre[sample-id]").each(function (e) {
        var sampleId = $(this).attr("sample-id");
        $(this).html($("#" + sampleId).contents());
    });

    SyntaxHighlighter.all();

    //hljs.initHighlightingOnLoad();
</script>
</body>
</html>